/// Ordered list of bird observation activities from Artportalen
/// (Activity_Birds, ap2_template_sv.xls version 4.17).
const List<String> kActivities = [
  'Bo, ägg/ungar',
  'Bo, hörda ungar',
  'Misslyckad häckning',
  'Ruvande',
  'Äggskal',
  'Föda åt ungar',
  'Bär exkrementsäck',
  'Besöker bebott bo',
  'Pulli/nyligen flygga ungar',
  'Nyligen använt bo',
  'Avledningsbeteende',
  'Bobygge',
  'Ruvfläckar',
  'Upprörd, varnande',
  'Bobesök?',
  'Parning/parningsceremonier',
  'Permanent revir',
  'Par i lämplig häckbiotop',
  'Spel/sång',
  'Obs i häcktid, lämplig biotop',
  'Rastande',
  'Stationär',
  'Förbiflygande',
  'Födosökande',
  'Lockläte, övriga läten',
  'Övernattning',
  'Revir, ej häckning',
  'Ringmärktes',
  'Individmärkt',
  'Sträckförsök',
  'Sträckande',
  'Sträckande N',
  'Sträckande NO',
  'Sträckande O',
  'Sträckande SO',
  'Sträckande S',
  'Sträckande SV',
  'Sträckande V',
  'Sträckande NV',
  'Död, krockat med kraftledning',
  'Död, krockat med vindkraftverk',
  'Död, krockat med fönster',
  'Död, krockat med fyr',
  'Trafikdödad',
  'Död, krockat med flygplan',
  'Död, krockat med staket',
  'Dödad av elektricitet',
  'Drunknad i fiskenät',
  'Dödad av predator',
  'Död av sjukdom/svält',
  'Funnen död',
  'Färska spår',
  'Äldre spår',
  'Färsk spillning',
  'Äldre spillning',
  'Gammalt bo',
];
